name: Update README on New Comment

on:
  issue_comment:
    types: [created]

jobs:
  update-readme:
    if: github.event.issue.title == 'Guestbook' # Check if the issue title is 'Guestbook'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with new comment
        run: |
          # Fetch existing comments from the Guestbook issue
          comments=$(curl -s https://api.github.com/repos/LovelyDev829/LovelyDev829/issues/1/comments | jq -r '.[] | "| [" + .user.login + "](https://github.com/" + .user.login + ") | \(.body) | \(.created_at)"')
          
          # Create or overwrite the README.md file
          echo "# Welcome to My GitHub Profile!" > README.md
          echo "## Recent Visitor Comments" >> README.md
          echo "" >> README.md
          echo "| Username | Comment | Date |" >> README.md
          echo "|----------|---------|------|" >> README.md
          echo "$comments" >> README.md

          # Add the button to add a note
          echo "[![Add a Note](https://img.shields.io/badge/Add%20a%20Note-Click%20Here-brightgreen)](https://github.com/LovelyDev829/LovelyDev829/issues/1)" >> README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet || git commit -m "Update README with latest guestbook comments"
          git push