name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update README
        run: |
          echo "# Welcome to My GitHub Profile!" > README.md
          echo "## Recent Visitor Comments" >> README.md
          echo "" >> README.md

          # Fetch comments from the Guestbook issue
          curl -s https://api.github.com/repos/LovelyDev829/LovelyDev829/issues/1/comments \
            | jq -r '.[] | "| [" + .user.login + "](https://github.com/" + .user.login + ") | \(.body) | \(.created_at)"' >> README.md

          echo "[![Add a Note](https://img.shields.io/badge/Add%20a%20Note-Click%20Here-brightgreen)](https://github.com/LovelyDev829/LovelyDev829/issues/1)" >> README.md

          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git commit -am "Update README with latest guestbook comments"
          git push